# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program(
        'llm-workload-example',
        ['core', 'network', 'internet', 'applications',
         'point-to-point', 'llm-workload'],
    )
    obj.source = 'llm-workload-example.cc'