simulation_end_time_ns=5000000000
simulation_seed=246810
satellite_network_dir="../gen_data/tiny_walker_1500_isls_plus_grid_5cities_algorithm_free_one_only_over_isls"
satellite_network_routes_dir="../gen_data/tiny_walker_1500_isls_plus_grid_5cities_algorithm_free_one_only_over_isls/dynamic_state_100ms_for_5s"
dynamic_state_update_interval_ns=100000000
isl_data_rate_megabit_per_s=10.0
gsl_data_rate_megabit_per_s=10.0
isl_max_queue_size_pkts=100
gsl_max_queue_size_pkts=100
enable_isl_utilization_tracking=false
tcp_socket_type=TcpNewReno
enable_llm_workload=true
llm_workload_schedule_filename="llm_workload_schedule.csv"
llm_workload_log_filename="llm.csv"
compute_alpha_ns_per_input_token=100000
compute_beta_ns_per_output_token=50000
compute_gamma_ns=10000000
enable_tcp_flow_scheduler=false
enable_udp_burst_scheduler=false
enable_pingmesh_scheduler=false
