"""
ns-3 config writer — produces a Phase-C-compatible
``config_ns3.properties`` file inside a run directory.

The exact list of recognised keys is dictated by Phase C's
``config_ns3_phase_c.properties`` template (which is itself consumed by
basic-sim's PropertiesConfig + the llm_workload module). We don't add
new keys; we just substitute the dashboard's UI values where the
template hardcodes specific values.
"""

from __future__ import annotations

import os
from pathlib import Path


def write_ns3_config(
    config,
    run_dir: Path,
    *,
    state_dir: Path,
    dynamic_state_dir: Path,
    schedule_filename: str = "llm_workload_schedule.csv",
    log_filename: str = "llm.csv",
    seed: int = 24681012,
) -> Path:
    """Render the Phase-C config file inside ``run_dir`` and return its path.

    Hypatia / basic-sim path conventions:

    - ``satellite_network_dir`` and ``satellite_network_routes_dir``
      are joined with the run dir at runtime
      (``topology-satellite-network.cc:43``):
      ``m_basicSimulation->GetRunDir() + "/" + <this value>``.
      So an absolute value silently becomes ``<run_dir>/<abs_path>`` —
      a nonexistent path, and Hypatia then aborts at line 147 with
      ``File tles.txt could not be opened``. Always pass a path
      *relative to the run dir*. We compute it with ``os.path.relpath``.
    - ``llm_workload_log_filename`` is *relative* to the run dir's
      ``logs_ns3/`` (Phase C convention). We pass just the basename.
    """
    run_dir_abs = run_dir.resolve()
    state_dir_rel = os.path.relpath(state_dir.resolve(), run_dir_abs)
    dynamic_state_dir_rel = os.path.relpath(dynamic_state_dir.resolve(), run_dir_abs)
    s = config.simulation
    c = config.compute

    sim_end_ns = s.duration_seconds * 1_000_000_000
    update_interval_ns = s.update_interval_ms * 1_000_000

    lines = [
        f"# Auto-generated by dashboard {Path(__file__).name}",
        f"# Experiment hash: {config.topology_hash()}",
        "",
        f"simulation_end_time_ns={sim_end_ns}",
        f"simulation_seed={seed}",
        "",
        f'satellite_network_dir="{state_dir_rel}"',
        f'satellite_network_routes_dir="{dynamic_state_dir_rel}"',
        f"dynamic_state_update_interval_ns={update_interval_ns}",
        "",
        # Link defaults match Phase C; the dashboard UI doesn't expose
        # these in v1 because changing them invalidates a lot of intuition.
        "isl_data_rate_megabit_per_s=10.0",
        "gsl_data_rate_megabit_per_s=10.0",
        "isl_max_queue_size_pkts=100",
        "gsl_max_queue_size_pkts=100",
        "",
        "enable_isl_utilization_tracking=false",
        "",
        "tcp_socket_type=TcpNewReno",
        "",
        "# Activate Phase C.",
        "enable_llm_workload=true",
        "enable_llm_response_loop=true",
        f'llm_workload_schedule_filename="{schedule_filename}"',
        f'llm_workload_log_filename="{log_filename}"',
        "",
        "# Compute model parameters (LLM cost: alpha*L_in + beta*L_out + gamma).",
        f"compute_alpha_ns_per_input_token={c.alpha_ns_per_input_token}",
        f"compute_beta_ns_per_output_token={c.beta_ns_per_output_token}",
        f"compute_gamma_ns={c.gamma_ns}",
        # Phase C's gather timeout matches the sim duration so a slow",
        # request is never artificially abandoned.",
        f"gather_timeout_ns={sim_end_ns}",
        "",
        "# Disable other schedulers.",
        "enable_tcp_flow_scheduler=false",
        "enable_udp_burst_scheduler=false",
        "enable_pingmesh_scheduler=false",
        "",
    ]

    run_dir.mkdir(parents=True, exist_ok=True)
    out = run_dir / "config_ns3.properties"
    out.write_text("\n".join(lines))
    return out
